[tool.poetry]
name = "rdm"
version = "0.1.0"
description = "null"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.0"
openpyxl = "^3.1.5"
python-gitlab = "^5.6.0"
tabulate = "^0.9.0"
xlsxwriter = "^3.2.2"
requests = "^2.32.3"
requests-toolbelt = "^1.0.0"
pandas = "^2.2.3"
xmind = "1.2.0"
pyautogui = "^0.9.54"


[[tool.poetry.source]]
name = "DataGrand"
url = "https://repo.datagrand.com/repository/pypi/simple"
priority = "supplemental"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
